apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-ns
spec:
  containers:
    - name: nginx
      image: nginx:latest # <-- This line pulls and runs the nginx container image
      ports:
        - containerPort: 80
