apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-ns
spec:
  selector:
    app.kubernetes.io/name: nginx #name is given on demployment.yml

  ports:
    - protocol: TCP
      port: 82       # cluster or host port
      targetPort: 80 #container port (node)