apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: online-shop
  labels:
    app: online-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-shop
      
#Pod--------#Pod--------#Pod------------#Pod----------#Pod------#Pod----#Pod

  template:
    metadata:
      name: online-shop
      namespace: online-shop
      labels:
        app: online-shop
    spec:
      containers:
      - name: online-shop
        image: mayursb330/online-shop
        ports:
        - containerPort: 80

