apiVersion: v1
kind: Service
metadata:
  name: online-shop
  namespace: online-shop

spec:
  type: NodePort
  selector:
    app: online-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

