apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx

spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx
      namespace: nginx-ns
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 # <-- This line pulls and runs the nginx container image
        ports:
        - containerPort: 80
